name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Replace Firebase Config
        run: |
          echo "🔧 Substituindo variáveis Firebase..."
          echo "📁 Conteúdo antes da substituição:"
          cat firebase-config.js
          
          # Substituir variáveis
          sed -i "s/\${FIREBASE_API_KEY}/${{ secrets.FIREBASE_API_KEY }}/g" firebase-config.js
          sed -i "s/\${FIREBASE_AUTH_DOMAIN}/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" firebase-config.js
          sed -i "s|\${FIREBASE_DATABASE_URL}|${{ secrets.FIREBASE_DATABASE_URL }}|g" firebase-config.js
          sed -i "s/\${FIREBASE_PROJECT_ID}/${{ secrets.FIREBASE_PROJECT_ID }}/g" firebase-config.js
          sed -i "s/\${FIREBASE_STORAGE_BUCKET}/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" firebase-config.js
          sed -i "s/\${FIREBASE_MESSAGING_SENDER_ID}/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" firebase-config.js
          sed -i "s/\${FIREBASE_APP_ID}/${{ secrets.FIREBASE_APP_ID }}/g" firebase-config.js
          
          echo "📁 Conteúdo após a substituição:"
          cat firebase-config.js
          
          echo "✅ Substituição concluída"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4